Test malicious
awslabs/graphstorm pull request #425
Opened 2023-09-08 20:54 UTC by JCy1rus

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-11 20:13 UTC, classicsong commented on .github/workflows/continuous-integration.yml
> +      (github.event.label.name != 'draft'
Should this also be ```pull_request.```?

2023-09-11 20:27 UTC, thvasilo requested changes

2023-09-11 20:27 UTC, thvasilo commented on .github/workflows/continuous-integration.yml
> +      && github.event_name == 'pull_request_target'
I don't think we should be using this way to check the event. The [official guidelines](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) from Github security suggest using:

```yaml
on:
      pull_request_target:
        types: [labeled]

    jobs:
      build:
        name: Build and test
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
```

was there any issue with using this approach?

2023-09-11 22:16 UTC, thvasilo commented on .github/workflows/continuous-integration.yml
> +      && github.event_name == 'pull_request_target'
Discussed offline, I'm OK with using this approach to have the condition at the job level instead of the workflow level.

2023-09-12 17:32 UTC, thvasilo approved these changes
LGTM now. The workflow only triggers for push which requires write permissions, and for any PRs. When triggered the additional condition will ensure that only PRs with the `ready` tag will be able to run the CI.

2023-09-12 18:57 UTC, merged