[GSProcessing] Bert Embedding
awslabs/graphstorm pull request #724
Opened 2024-02-02 21:12 UTC by jalencato

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-07 23:45 UTC, thvasilo requested changes

2024-02-07 23:51 UTC, jalencato commented on docs/source/gs-processing/developer/input-configuration.rst
> +                        to use ``tokenize_hf`` as the cpu version of torch can consume too much time.
We may need to keep the name of ```bert_hf```, as the gconstruct has the name ```bert_hf``` so we'd better keep the same here. (And that is why I use the name ```bert_hf```, from my perspective, I would say name like ```embedding_hf``` will be better.)

2024-02-07 23:53 UTC, jalencato commented on docs/source/gs-processing/developer/input-configuration.rst
> +                        to use ``tokenize_hf`` as the cpu version of torch can consume too much time.
Another thing is that I can anchor the cpu torch only to the emr serverless dockerfile. The size limitation only happens here. For SageMaker, we can use the torch gpu version.

2024-02-08 18:58 UTC, jalencato commented on graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
> +            lm_model = AutoModel.from_pretrained(bert_model, config)
I will test the performance on that. Actually, once the model cache is already downloaded in the cache directory, the huggingface will always retrieve the model cache in the directory so they will not download it through the internet anyway.

2024-02-08 21:51 UTC, jalencato commented on docs/source/gs-processing/developer/input-configuration.rst
>        - ``max_seq_length`` (Integer, required): It specifies the maximum number of tokens of the input.
Added check in the feature transformation

2024-02-08 23:40 UTC, thvasilo commented on docs/source/gs-processing/developer/input-configuration.rst
>        - ``max_seq_length`` (Integer, required): It specifies the maximum number of tokens of the input.
Let's also suggest a value here, like 128 or 256.

2024-02-08 23:44 UTC, thvasilo commented on graphstorm-processing/pyproject.toml
> +torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.1.2%2Bcpu-cp39-cp39-linux_x86_64.whl"}
Have we tested if this now works on Mac M1 laptops?

2024-02-08 23:55 UTC, jalencato commented on docs/source/gs-processing/developer/input-configuration.rst
>        - ``max_seq_length`` (Integer, required): It specifies the maximum number of tokens of the input.
Add a suggestion to provide a length larger than the longest, otherwise 128.

2024-02-09 00:02 UTC, thvasilo commented on graphstorm-processing/pyproject.toml
> +torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.1.2%2Bcpu-cp39-cp39-linux_x86_64.whl"}
Let's go with the platform-safe:

```suggestion
torch = [
    { url = "https://download.pytorch.org/whl/cpu/torch-2.2.0%2Bcpu-cp39-cp39-linux_x86_64.whl", markers = "sys_platform == 'linux' and platform_machine != 'aarch64'"},
    { url = "https://download.pytorch.org/whl/cpu/torch-2.2.0%2Bcpu-cp39-cp39-linux_x86_64.whl", markers = "sys_platform == 'darwin' and platform_machine != 'arm64'"},
    { url = "https://download.pytorch.org/whl/cpu/torch-2.2.0-cp39-none-macosx_11_0_arm64.whl", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'"},
    { url = "https://download.pytorch.org/whl/cpu/torch-2.2.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", markers = "sys_platform == 'linux' and platform_machine == 'aarch64'"},
]
```

If there are image size issues we should solve them in the Dockerfile, not the project's dependencies.

2024-02-09 19:56 UTC, thvasilo approved these changes
LGTM now

2024-02-09 19:57 UTC, merged